#program
mobile_home:
    pattern:  /
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:home, template: home }
mobile_route:
    pattern:  /route/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:home, template: route }
mobile_search:
    pattern:  /search/{q}/{onglet}
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:search, q: null, onglet: null  }
mobile_program:
    pattern:  /program/{id}/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:program }
mobile_signin:
    pattern:  /signin/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:signin }
mobile_cinemaprogram:
    pattern:  /cinemaprogram/{id}/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:cinemaprogram }
mobile_notifs:
    pattern:  /notifs/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:notifs }
mobile_playlist:
    pattern:  /playlist/{access}/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:playlist }
mobile_selection:
    pattern:  /selection/{id}
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:selection, id: null }
mobile_tv:
    pattern:  /tv/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:tv }
mobile_cinema:
    pattern:  /cinema/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:cinema }
mobile_dialog:
    pattern:  /dialog/
    defaults: { _controller: SkreenHouseFactoryMobileBundle:Main:dialog }